ncu --set default -o ncu_render_bicycle_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/bicycle_30k --skip_train
ncu --set default -o ncu_render_bonsai_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/bonsai_30k --skip_train
ncu --set default -o ncu_render_counter_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/counter_30k --skip_train
ncu --set default -o ncu_render_flowers_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/flowers_30k --skip_train
ncu --set default -o ncu_render_garden_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/garden_30k --skip_train
ncu --set default -o ncu_render_kitchen_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/kitchen_30k --skip_train
ncu --set default -o ncu_render_room_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/room_30k --skip_train
ncu --set default -o ncu_render_stump_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/stump_30k --skip_train
ncu --set default -o ncu_render_treehill_30k --csv --page details --metrics smsp__sass_branch_targets_threads_divergent.sum  python ./render.py -m ../output_full/treehill_30k --skip_train
